name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: I would like...
    validations:
      required: true

  - type: dropdown
    id: tool
    attributes:
      label: Which tool/area?
      options:
        - JSON Tools
        - Python Compiler
        - React Playground
        - Go Compiler
        - AI Tools
        - General/UI
        - New Tool
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
          required: false